# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


title: 雨花老林
me: 雨花亭老林
email: cio@gpwzw.com
description: > # this means to ignore newlines until "baseurl:"
  独立手机应用游戏开发者
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.linchangyu.com" # the base hostname & protocol for your site
twitter_username: cheneylin
github_username: cheneylin
beian: 沪ICP备09021215号


# Build settings
markdown: kramdown
